1.24.0. fin db archive, fin db restore commands.
- Adds ability to take backup of and restore the whole data in the db container volume.
- IMAGE_CLI_DEFAULT constant introduced

Relates to #326

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-FIN_VERSION=1.23.0
+FIN_VERSION=1.24.0
 
 # Console colors
 red='\033[0;91m'
@@ -165,6 +165,7 @@ URL_WINPTY="https://github.com/rprichard/winpty/releases/download/${REQUIREMENTS
 IMAGE_SSH_AGENT=${IMAGE_SSH_AGENT:-docksal/ssh-agent:1.0}
 IMAGE_VHOST_PROXY=${IMAGE_VHOST_PROXY:-docksal/vhost-proxy:1.1}
 IMAGE_DNS=${IMAGE_DNS:-docksal/dns:1.0}
+IMAGE_CLI_DEFAULT="docksal/cli:1.3-php7"
 
 #---------------------------- Helper functions --------------------------------
 
@@ -1025,7 +1026,7 @@ show_help ()
 	printh "build" "Build or rebuild services (alias for 'docker-compose build')"
 
 	echo
-	printh "db <command>" "DB commands: import, dump, list, cli (${yellow}fin help db${NC})" "yellow"
+	printh "db <command>" "DB commands: import, dump, list, cli, archive, restore (${yellow}fin help db${NC})" "yellow"
 	printh "project <command>" "Projects management commands: list, create (${yellow}fin help project${NC})" "yellow"
 	if ! is_linux && ! is_docker_native; then
 		printh "vm <command>" "VM commands: start, stop, restart and more. See ${yellow}fin help vm${NC}" "yellow"
@@ -1343,6 +1344,8 @@ show_help_db ()
 	printh "dump [file]" "Dump the database into a file or stdout."
 	printh "list (ls)" "Show list of available databases."
 	printh "cli" "Open command line interface to the DB server."
+	printh "archive" "Will make archive of ALL data on the DB server and put it into a tar file."
+	printh "restore" "Will restore ALL data on the DB server from a tar file in a current directory."
 	echo
 	echo-green "Parameters:"
 	printh "--db=drupal" "Use another database (default is the one set with 'MYSQL_DATABASE')"
@@ -3483,7 +3486,7 @@ run_cli ()
 	[[ $1 == "-T" ]] && \
 		local no_tty=true && shift
 	# Set default image
-	local IMAGE="${IMAGE:-docksal/cli:1.3-php7}"
+	local IMAGE="${IMAGE:-$IMAGE_CLI_DEFAULT}"
 	local cmd="$@"
 
 	# Assume bash if no command was given
@@ -3659,6 +3662,73 @@ mysql_dump ()
 	if [[ "${ARGV[0]}" != "" ]]; then
 		[ $? -eq 0 ] && echo-rewrite-ok "Exporting..."
 	fi
+}
+
+# Takes backup of the MySQL db container volume and saves into a tar file
+mysql_archive ()
+{
+	local backup_file="${COMPOSE_PROJECT_NAME_SAFE}_db_1.tar"
+
+	echo-green "Preparing..."
+	volume_id=$(
+		# get all volume mounts for db container
+		docker inspect -f '{{ .Mounts }}' "${COMPOSE_PROJECT_NAME_SAFE}_db_1" |
+			# remove symbols []{ form the output
+			tr -d "[]{" |
+			# convert } symbols into line breaks
+			tr "}" "\n" |
+			# get the line containing /var/lib/mysql volume mount
+			grep /var/lib/mysql |
+			# print second fragment of that line (it's the volume id)
+			awk '{print $2}'
+	)
+	if_failed_error "Failed getting volume id for db container." "See error log above for details."
+
+	echo-green "Backing up..."
+	docker run --rm -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) \
+		--volume "$volume_id":/db_volume_data \
+		--volume $(pwd):/current_dir \
+		${IMAGE_CLI_DEFAULT} \
+		sudo tar cvf "/current_dir/${backup_file}" /db_volume_data
+	if_failed_error "Failed backing up db container." "See error log above for details."
+
+	chmod +w "${backup_file}"
+	echo-green "Backup written into ${backup_file}"
+}
+
+# Restores MySQL db container volume data from a tar file
+mysql_restore ()
+{
+	local backup_file="${COMPOSE_PROJECT_NAME_SAFE}_db_1.tar"
+	[[ ! -f "$backup_file" ]] && echo-error "File $backup_file was not found" && exit 1
+
+	echo-green "Preparing..."
+	stop || exit 1
+
+	volume_id=$(
+		# get all volume mounts for db container
+		docker inspect -f '{{ .Mounts }}' "${COMPOSE_PROJECT_NAME_SAFE}_db_1" |
+			# remove symbols []{ form the output
+			tr -d "[]{" |
+			# convert } symbols into line breaks
+			tr "}" "\n" |
+			# get the line containing /var/lib/mysql volume mount
+			grep /var/lib/mysql |
+			# print second fragment of that line (it's the volume id)
+			awk '{print $2}'
+	)
+	if_failed_error "Failed getting volume id for db container." "See error log above for details."
+
+	echo-green "Restoring..."
+	docker run --rm -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) \
+		--volume "$volume_id":/volume_data \
+		--volume $(pwd):/current_dir \
+		${IMAGE_CLI_DEFAULT} \
+		sudo tar xvf "/current_dir/${backup_file}" -C /volume_data --strip 1
+	if_failed_error "Failed restoring data for db container." "See error log above for details."
+
+	up
+	echo-green "Data was restored"
 }
 
 # Download script by URL and execute it
@@ -4705,6 +4775,14 @@ case "$1" in
 			dump)
 				shift
 				mysql_dump "$@"
+				;;
+			archive)
+				shift
+				mysql_archive
+				;;
+			restore)
+				shift
+				mysql_restore
 				;;
 			*)
 				show_help_db
